server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456

  thymeleaf:
    cache: false 
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 自动驼峰命名
  mapper-locations: classpath*:mybatis-mapper/*.xml # Add this line
  global-config:
    db-config:
      id-type: auto # 主键自增